image: "macaronios/terragon-minimal:latest-amd64"
prelude:
- luet i --sync-repos -y curl
package_dir: /{{ .Values.name }}
steps:
- |
  ARCH=amd64 && \
  RES=$(curl --no-progress-meter -L https://dl.min.io/client/mc/release/linux-${ARCH}/mc.RELEASE.{{ ( index .Values.labels "package.version" ) }} --output /usr/bin/mc -w '%{http_code}') && \
  eval 'if [[ $RES != "200" ]]; then exit 1 ; fi'
- >-
  chmod a+x /usr/bin/mc && mkdir /{{ .Values.name }}/usr/bin -p &&
  mv /usr/bin/mc /{{ .Values.name }}/usr/bin/mc
