image: macaronios/phoenix-minimal-devel:latest-amd64
prelude:
- >-
  anise i -y --sync-repos make upx-bin go ca-certificates git gcc-config binutils-libs linux-headers &&
  eval 'gcc-config 1 || true' && macaronictl env-update &&
  anise cleanup --purge-repos && eval 'mkdir /tmp || true' &&
  mkdir /go/src/github.com/{{ ( index .Values.labels "github.repo" ) }}/ -p &&
  cd /go/src/github.com/{{ ( index .Values.labels "github.repo" ) }}/ &&
  git clone https://github.com/{{ ( index .Values.labels "github.repo" ) }}/distrobuilder.git
env:
- GOPATH=/go
package_dir: /{{ .Values.name }}
steps:
- >-
  cd /go/src/github.com/{{ ( index .Values.labels "github.repo" ) }}/distrobuilder &&
  git checkout {{ ( index .Values.labels "github.tag" ) }} &&
  make default &&
  cd distrobuilder/ &&
  go build -v . &&
  mkdir /{{ .Values.name }}/usr/bin -p &&
  cp ./distrobuilder /{{ .Values.name }}/usr/bin/distrobuilder
