path: /build/build/swagger-dev-util-0.30.5+b3738f4.1.package.tar.zst
dependencies: []
compilespec:
  steps:
  - cd go-swagger && git checkout ${GIT_HASH} && go build -v ./cmd/swagger/ && mkdir
    -p /swagger/usr/bin && mv swagger /swagger/usr/bin/
  env:
  - GIT_HASH=b3738f44372a08a43ab2db192c88538991f000ec
  prelude:
  - luet i -y --sync-repos make go ca-certificates git && luet cleanup --purge-repos
    && mkdir /tmp && git clone https://github.com/go-swagger/go-swagger.git
  image: macaronios/terragon-testing-minimal:latest-amd64
  seed: macaronios/terragon-testing-minimal:latest-amd64
  package:
    id: 0
    name: swagger
    version: 0.30.5+b3738f4.1
    category: dev-util
    useflags: []
    state: ""
    packagerequires: []
    packageconflicts: []
    provides: []
    hidden: false
    annotations: {}
    path: ""
    description: ""
    uri:
    - https://github.com/go-swagger/go-swagger
    license: Apache-2.0
    buildtimestamp: 2023-07-07 07:50:04.281148791 +0000 UTC m=+349.018167708
    labels:
      git.hash: b3738f44372a08a43ab2db192c88538991f000ec
      github.owner: go-swagger
      github.repo: go-swagger
    treedir: ./packages
    repository: ""
  package_dir: /swagger
  retrieve: []
  unpack: false
  includes: []
  excludes: []
  build_options:
    pushimagerepository: luet/cache
    pullimagerepository:
    - luet/cache
    pullfirst: false
    keepimg: false
    push: false
    concurrency: 0
    compressiontype: ""
    wait: false
    onlydeps: false
    nodeps: false
    solveroptions: {}
    buildvaluesfile: []
    buildvalues:
    - {}
    packagetargetonly: false
    rebuild: false
    backendargs: []
    backendtype: ""
    templatesfolder: []
  copy: []
  requires_final_images: false
checksums:
  sha256: ffca8b32ac61f212dded3177883b08285f93031dc44d64180afa26a4674d03bb
compressiontype: zstd
files:
- usr/bin/swagger
package_cacheimage: ""
runtime:
  id: 0
  name: swagger
  version: 0.30.5+b3738f4.1
  category: dev-util
  useflags: []
  state: ""
  packagerequires: []
  packageconflicts: []
  provides: []
  hidden: false
  annotations: {}
  path: ""
  description: ""
  uri:
  - https://github.com/go-swagger/go-swagger
  license: Apache-2.0
  buildtimestamp: ""
  labels:
    git.hash: b3738f44372a08a43ab2db192c88538991f000ec
    github.owner: go-swagger
    github.repo: go-swagger
  treedir: ""
  repository: ""
