image: macaronios/terragon-testing-minimal:latest-amd64
package_dir: /{{.Values.name}}

prelude:
- >-
  anise i -y --sync-repos make ca-certificates git tar &&
  anise cleanup --purge-repos && mkdir /tmp

steps:
- | 
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   mkdir -p /${PACKAGE_NAME}/usr/bin && \
   TRAEFIK_ARCH=amd64 && \
   curl -L https://github.com/{{ .Values.name }}/{{ .Values.name }}/releases/download/v${PACKAGE_VERSION}/{{ .Values.name }}_v${PACKAGE_VERSION}_linux_${TRAEFIK_ARCH}.tar.gz \
   -o {{ .Values.name }}.tar.gz && \
   tar xvzf {{ .Values.name }}.tar.gz && \
   mv {{ .Values.name }} /${PACKAGE_NAME}/usr/bin/ && \
   chmod +x /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME}
