image: macaronios/terragon-testing-minimal:latest-amd64
prelude:
- >-
  anise i -y --sync-repos make upx-bin go ca-certificates git &&
  anise cleanup --purge-repos &&
  git clone https://github.com/macaroni-os/anise
package_dir: /{{ .Values.name }}
steps:
- >-
  PACKAGE_VERSION=${PACKAGE_VERSION%\+*} &&
  cd anise && git checkout v"${PACKAGE_VERSION}" &&
  make build-build-small &&
  mkdir -p /{{ .Values.name }}/usr/bin &&
  mv anise-build/anise-build /{{ .Values.name }}/usr/bin/anise-build
