image: macaronios/terragon-minimal:latest-amd64
prelude:
- >-
  luet repo update &&
  luet i make sys-devel-1.13/automake sys-devel-2.69/autoconf git m4 virtual/base bash &&
  luet cleanup --purge-repos &&
  mkdir /root
- >-
  PACKAGE_VERSION=${PACKAGE_VERSION%\+*} &&
  git config --global advice.detachedHead false &&
  git clone https://github.com/{{ ( index .Values.labels "github.owner" ) }}/{{ ( index .Values.labels "github.repo" ) }}.git --depth 1 -b v$PACKAGE_VERSION /dbrm
env:
- LUET_YES=true
- DBRM_DEFAULT_CONFPATH=/etc/dbrm.conf
package_dir: /{{ .Values.name }}
steps:
- >-
  mkdir -p /{{ .Values.name }}/ &&
  cd /dbrm &&
  aclocal &&
  autoconf &&
  automake --add-missing &&
  ./configure --with-configfile-path=$DBRM_DEFAULT_CONFPATH --prefix=/usr &&
  make &&
  DESTDIR=/{{ .Values.name }}/ make install
