image: macaronios/terragon-testing-minimal:latest-amd64
prelude:
- >-
  luet i -y --sync-repos make upx-bin go ca-certificates git &&
  luet cleanup --purge-repos && mkdir /tmp &&
  git clone https://github.com/geaaru/luet
package_dir: /{{ .Values.name }}
steps:
- >-
  PACKAGE_VERSION=${PACKAGE_VERSION%\+*} &&
  cd luet && git checkout v"${PACKAGE_VERSION}-geaaru" &&
  make build &&
  mkdir -p /{{ .Values.name }}/usr/bin &&
  mv luet /{{ .Values.name }}/usr/bin/luet &&
  cd /{{ .Values.name }}/usr/bin &&
  ln -s luet anise
