image: "golang"
prelude:
- >-
  apt-get update &&
  apt-get install -y git make &&
  git clone https://github.com/{{ ( index .Values.labels "github.repo" ) }}/{{ .Values.name }}.git &&
  cd {{ .Values.name }} && git checkout "${GIT_TAG%\+*}" &&
  make build &&
  mkdir /{{ .Values.name }}/usr/bin -p &&
  cp {{ .Values.name }} /{{ .Values.name }}/usr/bin/
env:
- GIT_TAG=v{{ .Values.version }}
package_dir: /{{ .Values.name }}
