image: macaronios/terragon-minimal:latest-amd64
prelude:
- >-
  luet repo update &&
  luet i -y upx-bin git make go virtual/base &&
  git clone https://github.com/geaaru/entities
package_dir: /entities
steps:
- >-
  PACKAGE_VERSION=${PACKAGE_VERSION%\+*} &&
  cd entities && git checkout v"${PACKAGE_VERSION}"-{{ ( index .Values.labels "github.owner" ) }} &&
  make build-small &&
  mkdir /entities/usr/bin -p &&
  mv entities /entities/usr/bin/entities
