image: macaronios/terragon-testing-minimal:latest-amd64
prelude:
- >-
  anise i -y --sync-repos make upx-bin go ca-certificates git &&
  anise cleanup --purge-repos && eval 'mkdir /tmp || true' &&
  mkdir /go/src/github.com/{{ ( index .Values.labels "github.repo" ) }}/ -p &&
  cd /go/src/github.com/{{ ( index .Values.labels "github.repo" ) }}/ &&
  git clone https://github.com/{{ ( index .Values.labels "github.repo" ) }}/distrobuilder.git
env:
- GOPATH=/go
- DEBIAN_FRONTEND=noninteractive
package_dir: /{{ .Values.name }}
steps:
- >-
  cd /go/src/github.com/{{ ( index .Values.labels "github.repo" ) }}/distrobuilder &&
  git checkout v${PACKAGE_VERSION%\+*} &&
  make &&
  mkdir /{{ .Values.name }}/usr/bin -p &&
  mv /go/bin/distrobuilder /{{ .Values.name }}/usr/bin/distrobuilder
