image: "alpine"
package_dir: /yq

prelude:
- apk add curl

steps:
- | 
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   YQ_ARCH="amd64" && \
   mkdir -p /${PACKAGE_NAME}/usr/bin && \
   curl -L https://github.com/mikefarah/${PACKAGE_NAME}/releases/download/${PACKAGE_VERSION}/yq_linux_${YQ_ARCH} -o /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME} && \
   chmod +x /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME}
