image: macaronios/terragon-testing-minimal:latest-amd64
prelude:
- >-
  luet i -y --sync-repos make upx-bin go ca-certificates git &&
  luet cleanup --purge-repos && mkdir /tmp &&
  git clone https://github.com/MottainaiCI/{{ .Values.name }}.git
env:
- GIT_HASH=v{{ .Values.version }}
package_dir: /{{ .Values.name }}
steps:
- >-
  cd {{ .Values.name }} &&
  git checkout "${GIT_HASH%\+*}" &&
  make build &&
  mkdir -p /{{ .Values.name }}/usr/bin &&
  mv {{ .Values.name }} /{{ .Values.name }}/usr/bin/{{ .Values.name }}
