image: "golang"
prelude:
- >-
  apt-get update &&
  apt-get install -y git make
- git clone https://github.com/MottainaiCI/{{ .Values.name }}.git
env:
- GIT_HASH=v{{ .Values.version }}
package_dir: /{{ .Values.name }}
steps:
- >-
  cd {{ .Values.name }} &&
  git checkout "${GIT_HASH%\+*}" &&
  make build &&
  mkdir -p /{{ .Values.name }}/usr/bin &&
  mv {{ .Values.name }} /{{ .Values.name }}/usr/bin/{{ .Values.name }}
